name: check

on:
  push:
    branches:
      - main
      - next

concurrency:
  group: "check"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Make CI Check
        run: make ci-check
