name: publish

on:
  push:
    branches:
      - main

concurrency:
  group: "publish"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        version: [gcloud]

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.version }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ matrix.version }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ matrix.version }}
